backend = "egl";

vsync = true;
detect-client-opacity = true;
corner-radius = 10;
use-damage = true;
detect-transient = true;
detect-client-leader = true;

fading = true;
fade-delta = 2;
fade-in-step = 0.01;
fade-out-step = 0.01;

rules = (
    { match = "focused != 1"; opacity = 0.95; },
    { match = "class_g = 'dwm' || fullscreen"; corner-radius = 0; },
    { match = "window_type = 'menu'"; opacity = 1; },
    { match = "class_g = 'mpv'"; opacity = 1; },
    );

animations = (
    {
    triggers = [ "show", "open" ];
    preset = "appear";
    },
    {
    triggers = [ "hide", "close" ];
    preset = "disappear";
    },
    )
