--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,WebMachineLearningNeuralNetwork,FluentOverlayScrollbar
--process-per-site
--force-device-scale-factor=2
