hwdec=vaapi
vo=gpu
gpu-api=vulkan
volume=50
save-position-on-quit
cache=yes
ytdl-format=ytdl
msg-level=ffmpeg=fatal
screenshot-jpeg-quality=100
sub-font="Source Han Serif CN"
osd-font="Source Han Serif CN"
